wamv_gps:
    - name: gps
      x: -1.0119
      y: 0
      z: 2.3
      R: 0
      P: 0
      Y: 0
wamv_imu:
    - name: ahrs8
      x: -0.65
      y: -0.0090664
      z: 1.3
      R: 0
      P: 0
      Y: 0

# note that camera and velodyne lidar position differs slightly from original asv due to 
# vrx constraints and lidar appearing in camera fov
wamv_camera:
    - name: left_cam
      x: 0.96
      y: 0.19162
      z: 1.32
      R: 0
      P: 0
      Y: 0
      
    - name: center_cam
      x: 0.90
      y: 0
      z: 1.32
      R: 0
      P: 0
      Y: 0

    - name: right_cam
      x: 0.96
      y: -0.20291
      z: 1.32
      R: 0
      P: 0
      Y: 0

lidar:
    - name: puck
      type: 16_beam
      x: 0.9
      y: 0
      z: 1.3
      R: 0
      P: 0
      Y: 0

    - name: ouster
      type: 32_beam
      x: -0.65
      y: 0
      z: 2.3
      R: 0
      P: 0
      Y: 0

wamv_ball_shooter:
    - name: ball_shooter
      x: 0.5
      y: -0.25
      z: 1.3
      pitch: ${radians(-20)}
      yaw: 0
