wamv_camera:
    - name: middle_camera
      x: 0.75
      y: 0.0
      z: 1.6
      P: ${radians(15)}
    - name: front_right_camera
      x: 0.75
      y: -0.3
      z: 1.6
      P: ${radians(15)}
    - name: front_left_camera
      x: 0.75
      y: 0.3
      z: 1.6
      P: ${radians(15)}
wamv_gps:
    - name: gps_wamv
      x: 0.3
      y: 0.0
      z: 1.3
wamv_imu:
    - name: imu_wamv
      x: 0.3
      y: 0.0
      z: 1.3
# wamv_p3d:
#     - name: p3d_wamv
lidar:
    - name: lidar_wamv
      x: 0.75
      y: 0.0
      z: 1.6
      type: 16_beam
      P: ${radians(15)}
wamv_pinger:
    - name: pinger
